use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'podFTDemo_Example' do
  pod 'podFTDemo', :path => '../'
  
  target 'podFTDemo_Tests' do
    inherit! :search_paths

    
  end
end
